### PR TITLE
Trying to set up Buildkite, take III

### PR DESCRIPTION
**Pull request by mcabbott**

### CODE REVIEW

**Comment by mcabbott** [comment]
Previously all tests passed on Buildkite, but this time something fails in the LoopVectorization tests:

https://buildkite.com/julialang/tullio-dot-jl/builds/4#0fa01514-6069-432d-a78d-9172270e38d5/169-316

**Comment by DilumAluthge** [comment]
Interesting. GitHub Actions uses Intel CPUs. But if I understand correctly, the Buildkite runners are using AMD CPUs. Perhaps we have found a LoopVectorization.jl bug that only occurs on AMD CPUs?

cc: @chriselrod

**Comment by DilumAluthge** [comment]
@mcabbott Can you add the following to the top of `test/runtests.jl`?

```julia
import InteractiveUtils

InteractiveUtils.versioninfo(; verbose = true)
```

You'll also need to add `InteractiveUtils` as a test-only dependency.

**Comment by mcabbott** [comment]
Done. But looks like p6000.gpuci3.julia.csail.mit.edu is an Intel machine. Failed run was on gtx1080.hydor.elis.ugent.be instead.

**Comment by DilumAluthge** [comment]
I'll ask the people that run those machines to give me the specs.

**Comment by DilumAluthge** [comment]
Interesting. It passed this time.

So it seems the bug doesn't occur on Intel chips (at least, not on the Intel chips that GitHub/Microsoft uses, and not the Intel chip on p6000.gpuci3.julia.csail.mit.edu).

I'll find out the specs of gtx1080.hydor.elis.ugent.be and report back.

**Comment by DilumAluthge** [comment]
I just realized the specs are already in the log.

Info for gtx1080.hydor.elis.ugent.be:
```
Julia Version 1.5.3
--
  | Commit 788b2c77c1 (2020-11-09 13:37 UTC)
  | Platform Info:
  | OS: Linux (x86_64-pc-linux-gnu)
  | CPU: Intel(R) Xeon(R) CPU E5-2637 v2 @ 3.50GHz
  | WORD_SIZE: 64
  | LIBM: libopenlibm
  | LLVM: libLLVM-9.0.1 (ORCJIT, ivybridge)
```

**Comment by DilumAluthge** [comment]
In contrast, the info for p6000.gpuci3.julia.csail.mit.edu:
```
Julia Version 1.5.3
--
  | Commit 788b2c77c1 (2020-11-09 13:37 UTC)
  | Platform Info:
  | OS: Linux (x86_64-pc-linux-gnu)
  | CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
  | WORD_SIZE: 64
  | LIBM: libopenlibm
  | LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

**Comment by DilumAluthge** [comment]
I don't know enough about CPUs to know how to interpret this.

@mcabbott @chriselrod See the info above.

**Comment by chriselrod** [comment]
That is a VectorizationBase bug.
The Intel(R) Xeon(R) CPU E5-2637 v2 @ 3.50GHz doesn't have the AVX2 instruction set, which provides 256-bit SIMD integer operations.
So LoopVectorization just tries to do everything with scalars.

**Comment by chriselrod** [comment]
LoopVectorization 0.9.8 should hopefully fix it, but neither I nor CI actually tested on a computer without AVX2.

**Comment by mcabbott** [comment]
Great! 

Closing this as it was just a test to trigger CI.

**Pull request closed without merging**
