### PR TITLE
Debug a CI crash?

### LINKED ISSUE #73: TODO: reenable ALL tests on Julia 1.6 and Julia nightly
In #72, we disabled some tests on Julia nightly because they were causing CI to time out.

Once everything is working on Julia nightly, we should reenable ALL tests.

### PR DESCRIPTION
**Pull request by mcabbott**
Re-enabling some things skipped in #57 

Closes #73

### CODE REVIEW

**Comment by chriselrod** [comment]
As an aside, it may be worth adding the option to use LoopVectorization's threads.
But it won't necessarily be faster until I get around to adding cache-level blocking, e.g. Tullio was ahead above 1000x1000 or so for matrix multiplication on my computer:
Screenshot_2021-03-16 Gadfly Plot

**Comment by mcabbott** [comment]
Would indeed be good to have such an option, impressive stuff!

Re errors, after last commit allowing LV 0.12, there are some in https://github.com/mcabbott/Tullio.jl/pull/79/checks?check_run_id=2158318303  from `test/parsing.jl`. Would try to boil some down but at present my only computer is an M1 mac on which LV doesn't compile.

**Comment by chriselrod** [comment]
> Would try to boil some down but at present my only computer is an M1 mac on which LV doesn't compile.

I'd appreciate that, especially if you have a workflow for it. Tullio's output isn't the easiest to navigate (neither is LV's, hard problem to avoid with metaprogramming).

Any idea why that is? Both with native Julia and under Rosetta?
I was considering buying a Mac Mini to setup with buildkite for running CI jobs, but I'd prefer to wait to buy an ARM CPU until I can get one with SVE.

**Comment by mcabbott** [comment]
Oh good point, I was seeing how far I could get without Rosetta, but with it, I can indeed run things. 

The extent of my workflow is to look at what `@tullio <expr> verbose=2 grad=false` prints out, and trim that. Perhaps it could be more organised somehow! 

With native Julia, I think the first hurdle is that HWloc.jl needs a library via BinaryBuilder. Have been meaning to learn a little how all that works, but haven't yet. I can download and build `hwloc` natively, outside of Julia, so I think it's just a plumbing problem of some sort.

**Comment by chriselrod** [comment]
Ah. Do any BinaryBuilder packages work yet? Looking at the ARM issue, the [most recent binary builder comment](https://github.com/JuliaLang/julia/issues/36617#issuecomment-784614798) seems to imply they don't (i.e., they haven't been built for Apple ARM yet).

**Comment by mcabbott** [comment]
None that I have tried work, at the moment. I don't understand whether they can be fixed piecemeal, or must wait for a global re-build.

**Comment by mcabbott** [comment]
Merged but not quite fixed? E.g.

https://github.com/mcabbott/Tullio.jl/pull/105/checks?check_run_id=2457882209
```
1h 17m 29s

  gradients.jl:335
229
  gradients.jl:349
230
ERROR: Package Tullio errored during testing (received signal: KILL)
```

**Pull request merged**
