### PR TITLE
Improvements to KernelAbstractions code?

### PR DESCRIPTION
**Pull request by mcabbott**
Untested.

### CODE REVIEW

**Comment by merckxiaan** [comment]
This is what I get with the `try 0` commit
```
julia> [f(a) for _ in 1:20]
ERROR: Waiting on the GPU for an CPU event to finish is currently not supported.
We have encountered deadlocks arising, due to interactions with the CUDA
driver. If you are certain that you are deadlock free, you can use `unsafe_wait`
instead.

Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] wait(::CUDADevice, ::KernelAbstractions.CPUEvent, ::Function, ::CuStream) at C:\Users\jules\.julia\packages\KernelAbstractions\bIZIO\src\backends\cuda.jl:91
 [3] wait(::CUDADevice, ::MultiEvent{Tuple{KernelAbstractions.CPUEvent}}, ::Function, ::CuStream) at C:\Users\jules\.julia\packages\KernelAbstractions\bIZIO\src\backends\cuda.jl:83
 [4] (::KernelAbstractions.Kernel{CUDADevice,KernelAbstractions.NDIteration.StaticSize{(256,)},KernelAbstractions.NDIteration.DynamicSize,var"#gpu_##��#352#3"})(::CuArray{Float32,2}, ::Vararg{Any,N} where N; ndrange::Tuple{Int64,Int64}, dependencies::KernelAbstractions.CPUEvent, workgroupsize::Nothing, progress::Function) at C:\Users\jules\.julia\packages\KernelAbstractions\bIZIO\src\backends\cuda.jl:206
 [5] ���! at C:\Users\jules\.julia\packages\Tullio\uvqiL\src\macro.jl:1000 [inlined]
 [6] ���! at C:\Users\jules\.julia\packages\Tullio\uvqiL\src\macro.jl:997 [inlined]
 [7] threader(::var"#���!#1", ::Type{CuArray{Float32,2}}, ::CuArray{Float32,2}, ::Tuple{CuArray{Float32,2},CuArray{Float32,2}}, ::Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}, ::Tuple{Base.OneTo{Int64}}, ::Function, ::Int64, ::Nothing) at C:\Users\jules\.julia\packages\Tullio\uvqiL\src\eval.jl:89
 [8] (::var"#ℳ��ℯ#10"{var"#���!#1"})(::CuArray{Float32,2}, ::CuArray{Float32,2}) at C:\Users\jules\.julia\packages\Tullio\uvqiL\src\macro.jl:802
 [9] (::Tullio.Eval{var"#ℳ��ℯ#10"{var"#���!#1"},var"#265#∇ℳ��ℯ#9"{var"#∇���!#5"}})(::CuArray{Float32,2}, ::Vararg{CuArray{Float32,2},N} where N) at C:\Users\jules\.julia\packages\Tullio\uvqiL\src\eval.jl:20
 [10] f(::CuArray{Float32,2}) at .\REPL[3]:1
 [11] (::var"#12#13")(::Int64) at .\none:0
 [12] iterate at .\generator.jl:47 [inlined]
 [13] collect(::Base.Generator{UnitRange{Int64},var"#12#13"}) at .\array.jl:686
 [14] top-level scope at REPL[4]:1
```

**Comment by mcabbott** [comment]
OK, thanks for trying! I have no idea, would have to fiddle a lot. It's possible some subset of these changes might run?

**Comment by merckxiaan** [comment]
I also ran right before `try 0` and commented here https://github.com/JuliaGPU/KernelAbstractions.jl/issues/108.
Trying out `CuDevice suggestions` gives the same error as `add Const to kernel arguments`.
I've got no clue about what's going on and I'm also not sure I can easily combine branches to test?

**Comment by mcabbott** [comment]
If feeling energetic, you could `] dev` this package and mess around locally?

`CuDevice` doesn't seem to show up in https://github.com/JuliaGPU/KernelAbstractions.jl/tree/master/examples, maybe it's new, I'm not sure. Maybe https://github.com/JuliaGPU/CUDA.jl/search?q=CuDevice&unscoped_q=CuDevice has clues.

**Comment by merckxiaan** [comment]
With my luck, the monkeys would've finished Shakespeare's work already.
I replaced `CuDevice(0)` with `CUDADevice()` and everything magically works!

As for making stuff const, I quickly ran Mason's CUDA example mentioned in #30 but there's seems to be no aprreciable increase in performance.
before `const`-fix (yet after `CUDADevice`-fix):
```
N = 2
  0.000379 seconds (133 CPU allocations: 4.453 KiB) #generated by Tullio
  0.000177 seconds (15 CPU allocations: 416 bytes) #CUBLAS
N = 10
  0.000506 seconds (167 CPU allocations: 4.984 KiB)
  0.000056 seconds (15 CPU allocations: 416 bytes) 
N = 50
  0.000216 seconds (133 CPU allocations: 4.453 KiB)
  0.000102 seconds (15 CPU allocations: 416 bytes)
N = 100
  0.000198 seconds (133 CPU allocations: 4.453 KiB)
  0.000061 seconds (15 CPU allocations: 416 bytes)
N = 200
  0.000521 seconds (133 CPU allocations: 4.453 KiB)
  0.000390 seconds (15 CPU allocations: 416 bytes)
N = 500
  0.002040 seconds (133 CPU allocations: 4.453 KiB)
  0.000284 seconds (15 CPU allocations: 416 bytes)
N = 1000
  0.014123 seconds (133 CPU allocations: 4.453 KiB)
  0.000747 seconds (15 CPU allocations: 416 bytes)
N = 2000
  0.119267 seconds (133 CPU allocations: 4.453 KiB)
  0.004502 seconds (15 CPU allocations: 416 bytes)
N = 5000
  2.391341 seconds (133 CPU allocations: 4.453 KiB)
  0.045763 seconds (15 CPU allocations: 416 bytes)
N = 10000
 19.480897 seconds (133 CPU allocations: 4.453 KiB)
  0.437446 seconds (15 CPU allocations: 416 bytes)
```

after `const`-fix:
```
N = 2
  0.000229 seconds (133 CPU allocations: 4.453 KiB)
  0.000291 seconds (15 CPU allocations: 416 bytes)
N = 10
  0.000325 seconds (133 CPU allocations: 4.453 KiB)
  0.000267 seconds (15 CPU allocations: 416 bytes)
N = 50
  0.000933 seconds (133 CPU allocations: 4.453 KiB)
  0.000186 seconds (15 CPU allocations: 416 bytes)
N = 100
  0.000517 seconds (133 CPU allocations: 4.453 KiB)
  0.000209 seconds (15 CPU allocations: 416 bytes)
N = 200
  0.000422 seconds (133 CPU allocations: 4.453 KiB)
  0.000278 seconds (15 CPU allocations: 416 bytes)
N = 500
  0.001739 seconds (133 CPU allocations: 4.453 KiB)
  0.000212 seconds (15 CPU allocations: 416 bytes)
N = 1000
  0.014014 seconds (133 CPU allocations: 4.453 KiB)
  0.000805 seconds (15 CPU allocations: 416 bytes)
N = 2000
  0.116392 seconds (133 CPU allocations: 4.453 KiB)
  0.004565 seconds (15 CPU allocations: 416 bytes)
N = 5000
  2.377929 seconds (133 CPU allocations: 4.453 KiB)
  0.044224 seconds (15 CPU allocations: 416 bytes)
N = 10000
 19.390380 seconds (133 CPU allocations: 4.453 KiB)
  0.434024 seconds (15 CPU allocations: 416 bytes)
```

**Comment by mcabbott** [comment]
Great, well spotted. 

Does this version fix https://github.com/JuliaGPU/KernelAbstractions.jl/issues/108 too? 

Thanks for checking the benchmark. I guess more complicated tricks are needed there somehow.

**Comment by merckxiaan** [comment]
> Does this version fix [JuliaGPU/KernelAbstractions.jl#108](https://github.com/JuliaGPU/KernelAbstractions.jl/issues/108) too?

It does!

 > CI is still unhappy it seems: https://gitlab.com/JuliaGPU/Tullio.jl/-/jobs/725753381

When I run these tests locally without the `const`-changes (but with `CUDADevice`), they pass.

**Comment by mcabbott** [comment]
OK, that's good news. And useful to know that `@Const` seems to be the problem here.

**Pull request merged**
